import { GameTheme, ItemType } from './types';
import { 
  AppleIcon,
  BallIcon,
  StarIcon,
  DiceIcon,
  CatIcon,
  DogIcon,
  FishIcon,
  BirdIcon,
  SunIcon,
  FlowerIcon,
  TreeIcon,
  IceCreamIcon,
  CarIcon,
  BoatIcon,
  PlaneIcon,
  TrainIcon,
  RocketIcon,
  PlanetIcon,
  MoonIcon,
  UfoIcon,
  PizzaIcon,
  BurgerIcon,
  DonutIcon,
  FriesIcon,
  SoccerIcon,
  BasketballIcon,
  TennisIcon,
  BaseballIcon,
  BookIcon,
  PencilIcon,
  BackpackIcon,
  RulerIcon,
  BananaIcon,
  OrangeFruitIcon,
  PearIcon,
  WatermelonIcon,
  CarrotIcon,
  TomatoIcon,
  CucumberIcon,
  EggplantIcon,
  CowIcon,
  PigIcon,
  SheepIcon,
  HorseIcon,
  LionIcon,
  ElephantIcon,
  GiraffeIcon,
  ZebraIcon,
  SharkIcon,
  WhaleIcon,
  DolphinIcon,
  OctopusIcon,
  BeeIcon,
  ButterflyIcon,
  LadybugIcon,
  SpiderIcon,
  GuitarIcon,
  PianoIcon,
  TrumpetIcon,
  FluteIcon,
  SweaterIcon,
  PantsIcon,
  DressIcon,
  BeanieIcon,
  ChairIcon,
  TableIcon,
  BedIcon,
  SofaIcon,
  CakeIcon,
  ChocolateIcon,
  LollipopIcon,
  PopcornIcon,
  FirefighterIcon,
  PoliceIcon,
  DoctorIcon,
  ChefIcon,
  EyeIcon,
  EarIcon,
  NoseIcon,
  MouthIcon
} from './components/GameIcons';

export const THEMES: GameTheme[] = [
  {
    id: 'classic',
    name: 'Ting & Sager',
    buckets: [
      {
        type: ItemType.APPLE,
        label: 'Æbler',
        color: 'bg-red-500',
        fill: '#ef4444',
        icon: AppleIcon,
      },
      {
        type: ItemType.BALL,
        label: 'Bolde',
        color: 'bg-blue-500',
        fill: '#3b82f6',
        icon: BallIcon,
      },
      {
        type: ItemType.STAR,
        label: 'Stjerner',
        color: 'bg-yellow-400',
        fill: '#facc15',
        icon: StarIcon,
      },
      {
        type: ItemType.DICE,
        label: 'Terninger',
        color: 'bg-purple-500',
        fill: '#a855f7',
        icon: DiceIcon,
      },
    ]
  },
  {
    id: 'animals',
    name: 'Dyrevenner',
    buckets: [
      {
        type: ItemType.CAT,
        label: 'Katte',
        color: 'bg-orange-400',
        fill: '#fb923c',
        icon: CatIcon,
      },
      {
        type: ItemType.DOG,
        label: 'Hunde',
        color: 'bg-yellow-700',
        fill: '#a16207',
        icon: DogIcon,
      },
      {
        type: ItemType.FISH,
        label: 'Fisk',
        color: 'bg-blue-400',
        fill: '#60a5fa',
        icon: FishIcon,
      },
      {
        type: ItemType.BIRD,
        label: 'Fugle',
        color: 'bg-green-400',
        fill: '#4ade80',
        icon: BirdIcon,
      },
    ]
  },
  {
    id: 'summer',
    name: 'Sommer',
    buckets: [
      {
        type: ItemType.SUN,
        label: 'Sole',
        color: 'bg-yellow-500',
        fill: '#eab308',
        icon: SunIcon,
      },
      {
        type: ItemType.FLOWER,
        label: 'Blomster',
        color: 'bg-pink-500',
        fill: '#ec4899',
        icon: FlowerIcon,
      },
      {
        type: ItemType.TREE,
        label: 'Træer',
        color: 'bg-green-600',
        fill: '#16a34a',
        icon: TreeIcon,
      },
      {
        type: ItemType.ICECREAM,
        label: 'Is',
        color: 'bg-rose-300',
        fill: '#fda4af',
        icon: IceCreamIcon,
      },
    ]
  },
  {
    id: 'vehicles',
    name: 'Køretøjer',
    buckets: [
      {
        type: ItemType.CAR,
        label: 'Biler',
        color: 'bg-red-600',
        fill: '#dc2626',
        icon: CarIcon,
      },
      {
        type: ItemType.BOAT,
        label: 'Både',
        color: 'bg-blue-600',
        fill: '#2563eb',
        icon: BoatIcon,
      },
      {
        type: ItemType.PLANE,
        label: 'Flyvere',
        color: 'bg-sky-400',
        fill: '#38bdf8',
        icon: PlaneIcon,
      },
      {
        type: ItemType.TRAIN,
        label: 'Tog',
        color: 'bg-green-700',
        fill: '#15803d',
        icon: TrainIcon,
      },
    ]
  },
  {
    id: 'space',
    name: 'Rummet',
    buckets: [
      {
        type: ItemType.ROCKET,
        label: 'Raketter',
        color: 'bg-orange-500',
        fill: '#f97316',
        icon: RocketIcon,
      },
      {
        type: ItemType.PLANET,
        label: 'Planeter',
        color: 'bg-purple-600',
        fill: '#9333ea',
        icon: PlanetIcon,
      },
      {
        type: ItemType.MOON,
        label: 'Måner',
        color: 'bg-slate-400',
        fill: '#94a3b8',
        icon: MoonIcon,
      },
      {
        type: ItemType.UFO,
        label: 'UFOer',
        color: 'bg-lime-500',
        fill: '#84cc16',
        icon: UfoIcon,
      },
    ]
  },
  {
    id: 'food',
    name: 'Hurtigmad',
    buckets: [
      {
        type: ItemType.PIZZA,
        label: 'Pizzaer',
        color: 'bg-orange-300',
        fill: '#fdba74',
        icon: PizzaIcon,
      },
      {
        type: ItemType.BURGER,
        label: 'Burgere',
        color: 'bg-yellow-600',
        fill: '#ca8a04',
        icon: BurgerIcon,
      },
      {
        type: ItemType.DONUT,
        label: 'Donuts',
        color: 'bg-pink-400',
        fill: '#f472b6',
        icon: DonutIcon,
      },
      {
        type: ItemType.FRIES,
        label: 'Pomfritter',
        color: 'bg-red-500',
        fill: '#ef4444',
        icon: FriesIcon,
      },
    ]
  },
  {
    id: 'sports',
    name: 'Sport',
    buckets: [
      {
        type: ItemType.SOCCER,
        label: 'Fodbolde',
        color: 'bg-gray-800',
        fill: '#1f2937',
        icon: SoccerIcon,
      },
      {
        type: ItemType.BASKETBALL,
        label: 'Basketbolde',
        color: 'bg-orange-600',
        fill: '#ea580c',
        icon: BasketballIcon,
      },
      {
        type: ItemType.TENNIS,
        label: 'Tennisbolde',
        color: 'bg-lime-400',
        fill: '#a3e635',
        icon: TennisIcon,
      },
      {
        type: ItemType.BASEBALL,
        label: 'Baseballbolde',
        color: 'bg-stone-400',
        fill: '#a8a29e',
        icon: BaseballIcon,
      },
    ]
  },
  {
    id: 'school',
    name: 'Skole',
    buckets: [
      {
        type: ItemType.BOOK,
        label: 'Bøger',
        color: 'bg-blue-700',
        fill: '#1d4ed8',
        icon: BookIcon,
      },
      {
        type: ItemType.PENCIL,
        label: 'Blyanter',
        color: 'bg-yellow-300',
        fill: '#fde047',
        icon: PencilIcon,
      },
      {
        type: ItemType.BACKPACK,
        label: 'Tasker',
        color: 'bg-red-400',
        fill: '#f87171',
        icon: BackpackIcon,
      },
      {
        type: ItemType.RULER,
        label: 'Linealer',
        color: 'bg-amber-200',
        fill: '#fde68a',
        icon: RulerIcon,
      },
    ]
  },
  {
    id: 'fruits',
    name: 'Frugter',
    buckets: [
      {
        type: ItemType.BANANA,
        label: 'Bananer',
        color: 'bg-yellow-400',
        fill: '#facc15',
        icon: BananaIcon,
      },
      {
        type: ItemType.ORANGE_FRUIT,
        label: 'Appelsiner',
        color: 'bg-orange-500',
        fill: '#f97316',
        icon: OrangeFruitIcon,
      },
      {
        type: ItemType.PEAR,
        label: 'Pærer',
        color: 'bg-lime-500',
        fill: '#84cc16',
        icon: PearIcon,
      },
      {
        type: ItemType.WATERMELON,
        label: 'Meloner',
        color: 'bg-red-400',
        fill: '#f87171',
        icon: WatermelonIcon,
      },
    ]
  },
  {
    id: 'vegetables',
    name: 'Grøntsager',
    buckets: [
      {
        type: ItemType.CARROT,
        label: 'Gulerødder',
        color: 'bg-orange-500',
        fill: '#f97316',
        icon: CarrotIcon,
      },
      {
        type: ItemType.TOMATO,
        label: 'Tomater',
        color: 'bg-red-500',
        fill: '#ef4444',
        icon: TomatoIcon,
      },
      {
        type: ItemType.CUCUMBER,
        label: 'Agurker',
        color: 'bg-emerald-500',
        fill: '#10b981',
        icon: CucumberIcon,
      },
      {
        type: ItemType.EGGPLANT,
        label: 'Auberginer',
        color: 'bg-purple-600',
        fill: '#9333ea',
        icon: EggplantIcon,
      },
    ]
  },
  {
    id: 'farm_animals',
    name: 'Gårdens Dyr',
    buckets: [
      {
        type: ItemType.COW,
        label: 'Køer',
        color: 'bg-amber-700',
        fill: '#b45309',
        icon: CowIcon,
      },
      {
        type: ItemType.PIG,
        label: 'Grise',
        color: 'bg-pink-400',
        fill: '#f472b6',
        icon: PigIcon,
      },
      {
        type: ItemType.SHEEP,
        label: 'Får',
        color: 'bg-slate-400',
        fill: '#94a3b8',
        icon: SheepIcon,
      },
      {
        type: ItemType.HORSE,
        label: 'Heste',
        color: 'bg-yellow-800',
        fill: '#854d0e',
        icon: HorseIcon,
      },
    ]
  },
  {
    id: 'wild_animals',
    name: 'Savannens Dyr',
    buckets: [
      {
        type: ItemType.LION,
        label: 'Løver',
        color: 'bg-amber-500',
        fill: '#f59e0b',
        icon: LionIcon,
      },
      {
        type: ItemType.ELEPHANT,
        label: 'Elefanter',
        color: 'bg-blue-300',
        fill: '#93c5fd',
        icon: ElephantIcon,
      },
      {
        type: ItemType.GIRAFFE,
        label: 'Giraffer',
        color: 'bg-yellow-500',
        fill: '#eab308',
        icon: GiraffeIcon,
      },
      {
        type: ItemType.ZEBRA,
        label: 'Zebraer',
        color: 'bg-slate-800',
        fill: '#1e293b',
        icon: ZebraIcon,
      },
    ]
  },
  {
    id: 'sea_animals',
    name: 'Havets Dyr',
    buckets: [
      {
        type: ItemType.SHARK,
        label: 'Hajer',
        color: 'bg-sky-500',
        fill: '#0ea5e9',
        icon: SharkIcon,
      },
      {
        type: ItemType.WHALE,
        label: 'Hvaler',
        color: 'bg-indigo-400',
        fill: '#818cf8',
        icon: WhaleIcon,
      },
      {
        type: ItemType.DOLPHIN,
        label: 'Delfiner',
        color: 'bg-cyan-400',
        fill: '#22d3ee',
        icon: DolphinIcon,
      },
      {
        type: ItemType.OCTOPUS,
        label: 'Blæksprutter',
        color: 'bg-purple-500',
        fill: '#a855f7',
        icon: OctopusIcon,
      },
    ]
  },
  {
    id: 'insects',
    name: 'Insekter',
    buckets: [
      {
        type: ItemType.BEE,
        label: 'Bier',
        color: 'bg-amber-400',
        fill: '#fbbf24',
        icon: BeeIcon,
      },
      {
        type: ItemType.BUTTERFLY,
        label: 'Sommerfugle',
        color: 'bg-fuchsia-400',
        fill: '#e879f9',
        icon: ButterflyIcon,
      },
      {
        type: ItemType.LADYBUG,
        label: 'Mariehøns',
        color: 'bg-red-500',
        fill: '#ef4444',
        icon: LadybugIcon,
      },
      {
        type: ItemType.SPIDER,
        label: 'Edderkopper',
        color: 'bg-slate-700',
        fill: '#334155',
        icon: SpiderIcon,
      },
    ]
  },
  {
    id: 'music',
    name: 'Musikinstrumenter',
    buckets: [
      {
        type: ItemType.GUITAR,
        label: 'Guitarer',
        color: 'bg-amber-600',
        fill: '#d97706',
        icon: GuitarIcon,
      },
      {
        type: ItemType.PIANO,
        label: 'Klaverer',
        color: 'bg-slate-900',
        fill: '#0f172a',
        icon: PianoIcon,
      },
      {
        type: ItemType.TRUMPET,
        label: 'Trompeter',
        color: 'bg-yellow-500',
        fill: '#eab308',
        icon: TrumpetIcon,
      },
      {
        type: ItemType.FLUTE,
        label: 'Fløjter',
        color: 'bg-teal-500',
        fill: '#14b8a6',
        icon: FluteIcon,
      },
    ]
  },
  {
    id: 'clothes',
    name: 'Tøj',
    buckets: [
      {
        type: ItemType.SWEATER,
        label: 'Trøjer',
        color: 'bg-blue-500',
        fill: '#3b82f6',
        icon: SweaterIcon,
      },
      {
        type: ItemType.PANTS,
        label: 'Bukser',
        color: 'bg-indigo-600',
        fill: '#4f46e5',
        icon: PantsIcon,
      },
      {
        type: ItemType.DRESS,
        label: 'Kjoler',
        color: 'bg-rose-400',
        fill: '#fb7185',
        icon: DressIcon,
      },
      {
        type: ItemType.BEANIE,
        label: 'Huer',
        color: 'bg-teal-600',
        fill: '#0d9488',
        icon: BeanieIcon,
      },
    ]
  },
  {
    id: 'furniture',
    name: 'Møbler',
    buckets: [
      {
        type: ItemType.CHAIR,
        label: 'Stole',
        color: 'bg-amber-600',
        fill: '#d97706',
        icon: ChairIcon,
      },
      {
        type: ItemType.TABLE,
        label: 'Borde',
        color: 'bg-yellow-700',
        fill: '#a16207',
        icon: TableIcon,
      },
      {
        type: ItemType.BED,
        label: 'Senge',
        color: 'bg-blue-400',
        fill: '#60a5fa',
        icon: BedIcon,
      },
      {
        type: ItemType.SOFA,
        label: 'Sofaer',
        color: 'bg-red-400',
        fill: '#f87171',
        icon: SofaIcon,
      },
    ]
  },
  {
    id: 'sweets',
    name: 'Søde Sager',
    buckets: [
      {
        type: ItemType.CAKE,
        label: 'Kager',
        color: 'bg-pink-400',
        fill: '#f472b6',
        icon: CakeIcon,
      },
      {
        type: ItemType.CHOCOLATE,
        label: 'Chokolade',
        color: 'bg-amber-800',
        fill: '#854d0e',
        icon: ChocolateIcon,
      },
      {
        type: ItemType.LOLLIPOP,
        label: 'Slikkepinde',
        color: 'bg-red-400',
        fill: '#f87171',
        icon: LollipopIcon,
      },
      {
        type: ItemType.POPCORN,
        label: 'Popcorn',
        color: 'bg-yellow-300',
        fill: '#fde047',
        icon: PopcornIcon,
      },
    ]
  },
  {
    id: 'professions',
    name: 'Erhverv',
    buckets: [
      {
        type: ItemType.FIREFIGHTER,
        label: 'Brandmænd',
        color: 'bg-red-600',
        fill: '#dc2626',
        icon: FirefighterIcon,
      },
      {
        type: ItemType.POLICE,
        label: 'Politi',
        color: 'bg-blue-700',
        fill: '#1d4ed8',
        icon: PoliceIcon,
      },
      {
        type: ItemType.DOCTOR,
        label: 'Læger',
        color: 'bg-emerald-500',
        fill: '#10b981',
        icon: DoctorIcon,
      },
      {
        type: ItemType.CHEF,
        label: 'Kokke',
        color: 'bg-amber-500',
        fill: '#f59e0b',
        icon: ChefIcon,
      },
    ]
  },
  {
    id: 'body',
    name: 'Kroppen',
    buckets: [
      {
        type: ItemType.EYE,
        label: 'Øjne',
        color: 'bg-sky-400',
        fill: '#38bdf8',
        icon: EyeIcon,
      },
      {
        type: ItemType.EAR,
        label: 'Ører',
        color: 'bg-rose-300',
        fill: '#fda4af',
        icon: EarIcon,
      },
      {
        type: ItemType.NOSE,
        label: 'Næser',
        color: 'bg-orange-300',
        fill: '#fdba74',
        icon: NoseIcon,
      },
      {
        type: ItemType.MOUTH,
        label: 'Munde',
        color: 'bg-red-500',
        fill: '#ef4444',
        icon: MouthIcon,
      },
    ]
  }
];

export const TOTAL_ITEMS_TO_SPAWN = 20;
// Fallback initial state
export const INITIAL_BUCKETS = THEMES[0].buckets;
